addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - libssl1.0.0

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - sudo cp `which g++-4.8` `which g++`
    - sudo bash ./installer.sh
    - wget 'https://sourceforge.net/projects/astyle/files/astyle/astyle%203.0/astyle_3.0_linux.tar.gz/download'
    - tar -xzvf download
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -r
    - git clone https://github.com/google/glog.git

before_script:
    - chmod +x make-all.sh

script:
    - ./make-all.sh

language: cpp
