sudo: required

dist: trusty

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - openssl
      - libssl-dev
      - libcurl4-openssl-dev
      - cmake
      - cmake-data

install:
    - sudo apt-get install g++-6
    - sudo bash ./installer.sh
    - wget 'https://sourceforge.net/projects/astyle/files/astyle/astyle%203.0/astyle_3.0_linux.tar.gz/download'
    - tar -xzvf download
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -r

before_script:
    - chmod +x make-all.sh

script:
    - ./make-all.sh

language: cpp
