before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - sudo bash ./installer/installer.sh
    - chmod +x make-all
    - git clone https://github.com/google/googletest.git
    - cd googletest
    - g++ -isystem googletest/include/ -Igoogletest -isystem googlemock/include/ -Igooglemock -pthread -c googlemock/src/gmock-all.cc
    - g++ -isystem googletest/include/ -Igoogletest -isystem googlemock/include/ -Igooglemock -pthread -c googletest/src/gtest-all.cc
    - ar -rv libgmock.a gtest-all.o gmock-all.o
    - cp libgmock.a ../test/
    - cd ..
    - wget 'https://sourceforge.net/projects/astyle/files/latest/download'
    - tar -zxvf download
    - cd astyle/build/gcc
    - make release
    - sudo make install
    - cd ../../../

script: 
    - sudo ./make-all

language: cpp
